export const FETCH_INIT_STATE = 'FETCH_INIT_STATE';
export const ADD_VOTE = 'ADD_VOTE';

export const NOTIFICATION_HIDE = 'NOTIFICATION_HIDE';
export const NOTIFICATION_SHOW = 'NOTIFICATION_SHOW';

export const FILTER = 'FILTER';