export const INCR = 'INCR';
export const CREATE = 'CREATE';
export const NOTIFICATION_VOTE = 'NOTIFICATION_VOTE';
export const NOTIFICATION_CREATED = 'NOTIFICATION_CREATED';
export const NOTIFICATION_HIDE = 'NOTIFICATION_HIDE';