export const NOTIFICATION_HIDE = 'NOTIFICATION_HIDE';
export const NOTIFICATION_SHOW = 'NOTIFICATION_SHOW';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK = 'AUTH_CHECK';

export const GET_ALL_BLOGS_SUCCESS = 'GET_ALL_BLOGS_SUCCESS';
export const GET_ALL_BLOGS_FAIL = 'GET_ALL_BLOGS_FAIL';
export const GET_ALL_BLOGS_CHECK = 'GET_ALL_BLOGS_CHECK';


export const BLOG_ACTION_START = 'BLOGS_ACTION_START';
export const BLOG_ACTION_FAIL = 'BLOGS_ACTION_FAIL';
export const BLOG_ACTION_LIKE = 'BLOGS_ACTION_LIKE';


export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_USER = 'GET_USER';
export const SET_USER = 'SET_USER';
export const RESET_USER = 'RESET_USER'


// export const CREATE_NEW_BLOG_FAIL = 'CREATE_NEW_BLOG_FAIL';
