POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNub3ciLCJpZCI6IjVkYjI4ZTNhNmU3NjUxMWY0NDQwZTA1MCIsImlhdCI6MTU3MTk4MjkzM30.mx3XRM7iWQr2nQ4FRemAC5ByWcf0-8PNmvM2OTOQYmw


{
    "title":"One more Dummy content",
    "author": "Profun",
    "url":"https://en.wikipedia.org/wiki/Blog",
    "likes":5,
    "userId":"5db28e3a6e76511f4440e050"
}