POST http://localhost:3003/api/comment
Content-Type: application/json
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNub3ciLCJpZCI6IjVkYjI4ZTNhNmU3NjUxMWY0NDQwZTA1MCIsImlhdCI6MTU3MjE2OTQ3MX0.lHkDmMK3h7rJ8T8D2AmIE67Iky-M5XzCVcsNjtGhZ9c


{
    "comment":"this comment would be with authenticated user",
    "blogId": "5db74e75e92dd605cca24716"    
}